use_frameworks!
platform :ios, '8.0'

target 'podTestLibrary_Example' do
  pod 'podTestLibrary', :path => '../'

  target 'podTestLibrary_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
